name: ecnas
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - anyio=3.5.0
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - comm=0.1.2
  - commonmark=0.9.1
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - fftw=3.3.9
  - flit-core=3.6.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - future=0.18.2
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.16.0
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_core=5.1.1
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.16.5
  - jupyterlab_widgets=1.0.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.87.0
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.2
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - nbclassic=0.4.8
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=22.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.2.2
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=2.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - rich=12.5.1
  - scipy=1.10.0
  - send2trash=1.8.0
  - setuptools=65.5.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow-base=2.10.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.2.2
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - wrapt=1.14.1
  - xz=5.2.8
  - yarl=1.8.1
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - ale-py==0.8.1
    - ax-platform==0.1.20
    - black==23.1.0
    - blis==0.7.9
    - botorch==0.4.0
    - box2d==2.3.2
    - box2d-kengz==2.3.3
    - box2d-py==2.3.5
    - cachetools==5.3.0
    - carbontracker==1.1.7
    - catalogue==2.0.8
    - cbor==1.0.0
    - charset-normalizer==2.1.1
    - chest==0.2.3
    - click==8.1.3
    - cloudpickle==2.2.1
    - cma==3.3.0
    - coloredlogs==15.0.1
    - comocma==0.5.1
    - confection==0.0.4
    - configspace==0.6.1
    - coverage==7.2.1
    - cwl-eval==1.0.12
    - cymem==2.0.7
    - cython==0.29.33
    - dash==2.8.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - data==0.4
    - decorator==4.4.2
    - deprecated==1.2.13
    - dill==0.3.6
    - empirical-attainment-func==0.3.7
    - exceptiongroup==1.1.0
    - fast-pareto==0.2.2
    - fasteners==0.18
    - filelock==3.12.0
    - flake8==6.0.0
    - flask==2.2.3
    - flatbuffers==23.1.21
    - fsspec==2023.4.0
    - funcsigs==1.0.2
    - geocoder==1.38.1
    - glfw==2.5.6
    - google==3.0.0
    - google-api-core==2.11.0
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - google-cloud==0.34.0
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.7.0
    - google-cloud-vision==3.3.1
    - google-crc32c==1.5.0
    - google-resumable-media==2.4.1
    - googleapis-common-protos==1.58.0
    - gpytorch==1.8.0
    - grpcio==1.51.1
    - grpcio-status==1.51.1
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.27.1
    - gymnasium-notices==0.0.1
    - h5py==3.8.0
    - heapdict==1.0.1
    - huggingface-hub==0.14.0
    - humanfriendly==10.0
    - ijson==3.2.0.post0
    - imageio==2.25.1
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==5.1.0
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - ir-datasets==0.5.4
    - ir-measures==0.3.1
    - itsdangerous==2.1.2
    - jax==0.3.24
    - jax-jumpy==0.2.0
    - jaxlib==0.3.24
    - joblib==1.2.0
    - keras==2.11.0
    - kneed==0.8.2
    - langcodes==3.3.0
    - latex==0.7.0
    - lenspy==1.1.0
    - libclang==15.0.6.1
    - lightgbm==3.3.5
    - linear-operator==0.2.0
    - llvmlite==0.39.1
    - lz4==4.3.2
    - matchpy==0.5.5
    - mccabe==0.7.0
    - moarchiving==0.6.0
    - more-itertools==9.0.0
    - moviepy==1.0.3
    - mpmath==1.3.0
    - mujoco==2.2.0
    - mujoco-py==2.1.2.14
    - multipledispatch==0.6.0
    - multiset==2.1.1
    - murmurhash==1.0.9
    - mypy==1.0.1
    - mypy-extensions==1.0.0
    - nmslib==2.1.1
    - nptyping==1.4.4
    - numba==0.56.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - ofa==0.1.0-202203231606
    - onnxruntime==1.14.1
    - opencv-python==4.7.0.68
    - pandas==1.4.0
    - pathspec==0.11.0
    - pathy==0.10.1
    - patsy==0.5.3
    - plotly==5.13.0
    - pluggy==1.0.0
    - preshed==3.0.8
    - proglog==0.1.10
    - proto-plus==1.22.2
    - protobuf==3.19.6
    - psutil==5.9.4
    - py==1.11.0
    - pyasn1-modules==0.2.8
    - pyautocorpus==0.1.9
    - pybind11==2.6.1
    - pycodestyle==2.10.0
    - pydantic==1.10.7
    - pyfakefs==5.2.2
    - pyflakes==3.0.1
    - pygame==2.1.3.dev8
    - pyjnius==1.4.2
    - pynvml==11.4.1
    - pyopengl==3.1.6
    - pyqt5-sip==12.11.0
    - pyro-api==0.1.2
    - pyro-ppl==1.8.4
    - pyserini==0.21.0
    - pytest==7.0.1
    - pytest-cov==4.0.0
    - python-terrier==0.9.2
    - pytrec-eval-terrier==0.5.5
    - pytz==2022.6
    - pyyaml==6.0
    - ratelim==0.1.6
    - regex==2023.3.23
    - requests-mock==1.10.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.2.1
    - seaborn==0.12.2
    - sentencepiece==0.1.98
    - shimmy==0.2.1
    - shutilwhich==1.1.0
    - smart-open==6.3.0
    - spacy==3.5.2
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.4
    - srsly==2.4.6
    - statsmodels==0.13.5
    - swig==4.1.1
    - sympy==1.11.1
    - tempdir==0.7.1
    - tenacity==8.2.1
    - tensorboard==2.11.2
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.30.0
    - termcolor==2.2.0
    - thinc==8.1.9
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tokenizers==0.13.3
    - torch==1.13.1
    - torch-summary==1.4.5
    - torchvision==0.14.1
    - transformers==4.28.1
    - trec-car-tools==2.6
    - typeguard==2.13.3
    - typer==0.7.0
    - typish==1.9.3
    - unlzw3==0.2.2
    - urllib3==1.26.13
    - warc3-wet==0.2.3
    - warc3-wet-clueweb09==0.2.5
    - wasabi==1.1.1
    - wget==3.2
    - zipp==3.11.0
    - zlib-state==0.1.5
